In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("C:/Users/anuku/OneDrive/Desktop/Fated/Coding/Winter of Code/Datasets/nn_train.csv")

In [3]:
data

,ID,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,...,Feature_1017,Feature_1018,Feature_1019,Feature_1020,Feature_1021,Feature_1022,Feature_1023,Feature_1024,binary_label,class_label
0,1,81,109,91,96,107,97,103,95,100,...,114,93,91,98,72,92,78,78,0,5
1,2,168,168,169,169,170,171,172,172,175,...,44,44,44,44,44,44,44,44,0,9
2,3,14,20,32,6,27,6,5,34,15,...,63,64,63,60,54,48,43,41,0,5
3,4,60,109,157,126,82,80,70,58,37,...,105,102,99,98,100,105,111,114,1,8
4,5,63,72,86,75,93,77,75,67,62,...,108,109,102,106,96,91,102,89,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,79996,58,72,90,89,73,68,68,59,61,...,11,8,5,3,3,2,1,0,1,1
79996,79997,245,232,245,255,255,255,252,250,251,...,39,36,37,37,38,42,46,54,1,10
79997,79998,9,39,48,50,75,104,133,164,184,...,0,0,9,0,7,16,9,24,0,2
79998,79999,116,180,214,212,216,219,215,218,221,...,66,75,70,67,66,86,54,77,0,10
79999,80000,113,112,114,119,124,125,127,128,140,...,104,115,115,108,105,105,121,146,1,1

In [4]:
data=data.drop(columns='ID')

In [5]:
data

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Feature_10,...,Feature_1017,Feature_1018,Feature_1019,Feature_1020,Feature_1021,Feature_1022,Feature_1023,Feature_1024,binary_label,class_label
0,81,109,91,96,107,97,103,95,100,99,...,114,93,91,98,72,92,78,78,0,5
1,168,168,169,169,170,171,172,172,175,175,...,44,44,44,44,44,44,44,44,0,9
2,14,20,32,6,27,6,5,34,15,28,...,63,64,63,60,54,48,43,41,0,5
3,60,109,157,126,82,80,70,58,37,61,...,105,102,99,98,100,105,111,114,1,8
4,63,72,86,75,93,77,75,67,62,65,...,108,109,102,106,96,91,102,89,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,58,72,90,89,73,68,68,59,61,55,...,11,8,5,3,3,2,1,0,1,1
79996,245,232,245,255,255,255,252,250,251,255,...,39,36,37,37,38,42,46,54,1,10
79997,9,39,48,50,75,104,133,164,184,170,...,0,0,9,0,7,16,9,24,0,2
79998,116,180,214,212,216,219,215,218,221,215,...,66,75,70,67,66,86,54,77,0,10
79999,113,112,114,119,124,125,127,128,140,138,...,104,115,115,108,105,105,121,146,1,1

In [6]:
X=data.iloc[:,:-2].values

In [7]:
X

array([[ 81, 109,  91, ...,  92,  78,  78],
       [168, 168, 169, ...,  44,  44,  44],
       [ 14,  20,  32, ...,  48,  43,  41],
       ...,
       [  9,  39,  48, ...,  16,   9,  24],
       [116, 180, 214, ...,  86,  54,  77],
       [113, 112, 114, ..., 105, 121, 146]])

In [8]:
X=(X-np.mean(X,axis=0))/np.std(X,axis=0)
X

array([[-0.50084032, -0.10614544, -0.39079916, ..., -0.33368212,
        -0.55844268, -0.54238221],
       [ 0.75292181,  0.75635765,  0.7562259 , ..., -1.16661849,
        -1.14535402, -1.12059217],
       [-1.46638128, -1.40720943, -1.25842068, ..., -1.09720712,
        -1.16261612, -1.1716107 ],
       ...,
       [-1.53843658, -1.12945419, -1.02313349, ..., -1.65249803,
        -1.74952745, -1.46071568],
       [ 0.00354674,  0.93178201,  1.41797113, ..., -0.43779916,
        -0.97273304, -0.55938838],
       [-0.03968644, -0.06228935, -0.05257382, ..., -0.10809518,
         0.18382753,  0.61403773]])

In [9]:
Y_binary=data.iloc[:,-2].values
Y_multi=data.iloc[:,-1].values

In [10]:
def one_hot_encode(Y,num_classes):
    one_hot=np.zeros((Y.size,num_classes))
    one_hot[np.arange(Y.size),Y-1]=1  # Assuming classes are 1-indexed
    return one_hot

Y_multi_one_hot=one_hot_encode(Y_multi,10)

In [11]:
Y_multi_one_hot

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [12]:
split_index=int(0.8*len(X))
X_train,X_test=X[0:split_index,:],X[split_index:len(X),:]
Y_binary_train,Y_binary_test=Y_binary[0:split_index,],Y_binary[split_index:len(X),]
Y_multi_train,Y_multi_test=Y_multi_one_hot[0:split_index,],Y_multi_one_hot[split_index:len(X),]

In [13]:
input_size=1024
hidden_size1=512
output_size_binary=1
output_size_multi=10

In [14]:
np.random.seed(42)
w={
    "W1":np.random.randn(input_size,hidden_size1).astype(np.float32)*np.sqrt(2.0/input_size),
    "b1":np.zeros((1,hidden_size1),dtype=np.float32),
    "W_binary":np.random.randn(hidden_size1,output_size_binary).astype(np.float32)*np.sqrt(2.0/hidden_size1),
    "b_binary":np.zeros((1,output_size_binary),dtype=np.float32),
    "W_multi":np.random.randn(hidden_size1, output_size_multi).astype(np.float32)*np.sqrt(2.0/hidden_size1),
    "b_multi":np.zeros((1,output_size_multi),dtype=np.float32)
}

In [15]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [16]:
def softmax(z):
    exp_z=np.exp(z-np.max(z,axis=1,keepdims=True))
    return exp_z/np.sum(exp_z,axis=1,keepdims=True)

In [17]:
def relu(z):
    return np.maximum(0,z)

In [18]:
def forward_propagation(X,w):
    Z1=np.dot(X,w["W1"])+w["b1"]
    A1=relu(Z1)
    
    Z_binary=np.dot(A1,w["W_binary"])+w["b_binary"]
    A_binary=sigmoid(Z_binary)
    
    Z_multi=np.dot(A1,w["W_multi"])+w["b_multi"]
    A_multi=softmax(Z_multi)
    
    cache={"Z1":Z1,"A1":A1,"Z_binary":Z_binary,"A_binary":A_binary,"Z_multi":Z_multi,"A_multi":A_multi}
    return A_binary,A_multi,cache

In [19]:
def compute_cost(A_binary,Y_binary,A_multi,Y_multi_one_hot):
    m=Y_binary.shape[0]
    binary_cost=-np.mean(Y_binary*np.log(A_binary+1e-8)+(1-Y_binary)*np.log(1-A_binary+1e-8))
    multi_cost=-np.mean(np.sum(Y_multi_one_hot*np.log(A_multi+1e-8),axis=1))
    return binary_cost,multi_cost

In [20]:
def backward_propagation(X,Y_binary,Y_multi_one_hot,cache,w):
    m=X.shape[0]
    dZ_binary=cache["A_binary"]-Y_binary.reshape(-1,1)
    dW_binary=np.dot(cache["A1"].T,dZ_binary)/m
    db_binary=np.sum(dZ_binary,axis=0,keepdims=True)/m
    
    dZ_multi=cache["A_multi"]-Y_multi_one_hot
    dW_multi=np.dot(cache["A1"].T,dZ_multi)/m
    db_multi=np.sum(dZ_multi,axis=0,keepdims=True)/m
    
    dA1=np.dot(dZ_binary,w["W_binary"].T)+np.dot(dZ_multi,w["W_multi"].T)
    dZ1=dA1*(cache["Z1"]>0)
    dW1=np.dot(X.T,dZ1)/m
    db1=np.sum(dZ1,axis=0,keepdims=True)/m
    
    gradients={"dW1":dW1,"db1":db1,"dW_binary":dW_binary,"db_binary":db_binary,"dW_multi":dW_multi,"db_multi":db_multi}
    return gradients

In [21]:
def update_weights(w,gradients,learning_rate,beta1,beta2,epsilon,t,v,s):
    for key in w.keys():
        if key.startswith("W") or key.startswith("b"):
            v[key]=beta1*v[key]+(1-beta1)*gradients["d"+key]
            s[key]=beta2*s[key]+(1-beta2)*(gradients["d"+key]**2)
            v_corrected=v[key]/(1-beta1**t)
            s_corrected=s[key]/(1-beta2**t)
            w[key]-=learning_rate*v_corrected/(np.sqrt(s_corrected)+epsilon)
    return w,v,s

In [22]:
def mini_batch_generator(X,Y_binary,Y_multi_one_hot,batch_size):
    m=X.shape[0]
    indices=np.random.permutation(m)
    X_shuffled=X[indices]
    y_binary_shuffled=Y_binary[indices]
    y_multi_shuffled=Y_multi_one_hot[indices]
    for i in range(0,m,batch_size):
        end=i+batch_size
        yield X_shuffled[i:end],y_binary_shuffled[i:end],y_multi_shuffled[i:end]

In [23]:
def calculate_accuracy(Y_true,Y_pred):
    if Y_pred.shape[1]==1:
        Y_pred_class=(Y_pred>0.5).astype(int)
        return np.mean(Y_pred_class==Y_true.reshape(-1,1))
    else:
        Y_pred_class=np.argmax(Y_pred,axis=1)+1
        return np.mean(Y_pred_class==Y_true)

In [24]:
def train_model(X, Y_binary, Y_multi, w, epochs=30, batch_size=64, initial_learning_rate=0.001, beta1=0.9, beta2=0.999, epsilon=1e-8):
    v = {key: np.zeros_like(val) for key, val in w.items()}
    s = {key: np.zeros_like(val) for key, val in w.items()}

    learning_rate = initial_learning_rate

    for epoch in range(1, epochs + 1):
        epoch_binary_cost = 0
        epoch_multi_cost = 0
        num_batches = 0

        for X_batch, y_binary_batch, y_multi_batch_one_hot in mini_batch_generator(X, Y_binary, Y_multi, batch_size):
            A_binary, A_multi, cache = forward_propagation(X_batch, w)
            binary_cost, multi_cost = compute_cost(A_binary, y_binary_batch, A_multi, y_multi_batch_one_hot)
            gradients = backward_propagation(X_batch, y_binary_batch, y_multi_batch_one_hot, cache, w)
            w, v, s = update_weights(w, gradients, learning_rate, beta1, beta2, epsilon, epoch, v, s)

            epoch_binary_cost += binary_cost
            epoch_multi_cost += multi_cost
            num_batches += 1

        epoch_binary_cost /= num_batches
        epoch_multi_cost /= num_batches

        # Compute accuracy on the training set
        train_A_binary, train_A_multi, _ = forward_propagation(X_train, w)
        train_binary_accuracy = calculate_accuracy(Y_binary_train, train_A_binary)
        train_multi_accuracy = calculate_accuracy(np.argmax(Y_multi_train, axis=1) + 1, train_A_multi)

        # Compute accuracy on the test set
        test_A_binary, test_A_multi, _ = forward_propagation(X_test, w)
        test_binary_accuracy = calculate_accuracy(Y_binary_test, test_A_binary)
        test_multi_accuracy = calculate_accuracy(np.argmax(Y_multi_test, axis=1) + 1, test_A_multi)

        
        print(f"Epoch {epoch}: Binary Cost = {epoch_binary_cost:.4f}, Multi-class Cost = {epoch_multi_cost:.4f}, \
        Train Binary Accuracy = {train_binary_accuracy:.4f}, Train Multi-class Accuracy = {train_multi_accuracy:.4f}, \
        Test Binary Accuracy = {test_binary_accuracy:.4f}, Test Multi-class Accuracy = {test_multi_accuracy:.4f}")

    return w

In [ ]:
trained_weights = train_model(X_train, Y_binary_train, Y_multi_train, w, epochs=30, batch_size=64, initial_learning_rate=0.001, beta1=0.9, beta2=0.999, epsilon=1e-8)

Epoch 1: Binary Cost = 1.0041, Multi-class Cost = 1.7768,         Train Binary Accuracy = 0.7622, Train Multi-class Accuracy = 0.5141,         Test Binary Accuracy = 0.7432, Test Multi-class Accuracy = 0.4710
Epoch 2: Binary Cost = 1.0095, Multi-class Cost = 1.3968,         Train Binary Accuracy = 0.7744, Train Multi-class Accuracy = 0.5694,         Test Binary Accuracy = 0.7527, Test Multi-class Accuracy = 0.5092
Epoch 3: Binary Cost = 1.0375, Multi-class Cost = 1.2940,         Train Binary Accuracy = 0.7868, Train Multi-class Accuracy = 0.5953,         Test Binary Accuracy = 0.7544, Test Multi-class Accuracy = 0.5188
Epoch 4: Binary Cost = 1.0613, Multi-class Cost = 1.2245,         Train Binary Accuracy = 0.7983, Train Multi-class Accuracy = 0.6141,         Test Binary Accuracy = 0.7631, Test Multi-class Accuracy = 0.5251
Epoch 5: Binary Cost = 1.0812, Multi-class Cost = 1.1694,         Train Binary Accuracy = 0.8004, Train Multi-class Accuracy = 0.6321,         Test Binary Accuracy = 0.7632, Test Multi-class Accuracy = 0.5369
Epoch 6: Binary Cost = 1.1032, Multi-class Cost = 1.1236,         Train Binary Accuracy = 0.8105, Train Multi-class Accuracy = 0.6461,         Test Binary Accuracy = 0.7715, Test Multi-class Accuracy = 0.5329
Epoch 7: Binary Cost = 1.1264, Multi-class Cost = 1.0837,         Train Binary Accuracy = 0.8164, Train Multi-class Accuracy = 0.6622,         Test Binary Accuracy = 0.7709, Test Multi-class Accuracy = 0.5433

In [ ]:
test_A_binary, test_A_multi, _ = forward_propagation(X_test, trained_weights)
test_binary_accuracy = calculate_accuracy(Y_binary_test, test_A_binary)
test_multi_accuracy = calculate_accuracy(np.argmax(Y_multi_test, axis=1) + 1, test_A_multi)

print(f"Final Test Binary Accuracy: {test_binary_accuracy:.4f}")
print(f"Final Test Multi-class Accuracy: {test_multi_accuracy:.4f}")